site_name: Yuunagi Library
site_description: 个人的数字图书馆
site_author: Yuunagi
site_url: https://uynajgi.github.io/yuulibrary/
docs_dir: docs

use_directory_urls: false

theme:
  name: material
  language: zh
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 切换浅色模式
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.prune
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      separator: '[\s​\-]'
  - tags
  - social:
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [CI, false]

nav:
  - 首页: index.md
  - 书籍:
    - 机器学习:
      - 强化学习入门:
        - 封面: books/ml/rl-intro/index.md
        - 前言: books/ml/rl-intro/preface.md
        - 常用符号: books/ml/rl-intro/notations.md
        - 算法列表: books/ml/rl-intro/algorithms.md
        - 第1章 · 概述: books/ml/rl-intro/ch01.md
        - 第2章 · 从一个示例到马尔可夫决策过程: books/ml/rl-intro/ch02.md
        - 第3章 · 动态规划寻找最优策略: books/ml/rl-intro/ch03.md
        - 第4章 · 不基于模型的预测: books/ml/rl-intro/ch04.md
        - 第5章 · 无模型的控制: books/ml/rl-intro/ch05.md
        - 第6章 · 价值函数的近似表示: books/ml/rl-intro/ch06.md
        - 第7章 · 基于策略梯度的深度强化学习: books/ml/rl-intro/ch07.md
        - 第8章 · 基于模型的学习和规划: books/ml/rl-intro/ch08.md
        - 第9章 · 探索与利用: books/ml/rl-intro/ch09.md
        - 第10章 · Alpha Zero算法实战: books/ml/rl-intro/ch10.md
    - 金融经济:
      - 期权期货及其他衍生产品:
        - 封面: books/finance/options-futures-derivatives/index.md
        - 第1章 · 引言: books/finance/options-futures-derivatives/ch01.md
        - 第2章 · 期货市场的运作机制: books/finance/options-futures-derivatives/ch02.md
        - 第3章 · 利用期货的对冲策略: books/finance/options-futures-derivatives/ch03.md
        - 第4章 · 利率: books/finance/options-futures-derivatives/ch04.md
        - 第5章 · 远期和期货价格的确定: books/finance/options-futures-derivatives/ch05.md
        - 第6章 · 利率期货: books/finance/options-futures-derivatives/ch06.md
        - 第7章 · 互换: books/finance/options-futures-derivatives/ch07.md
        - 第8章 · 证券化与2007年信用危机: books/finance/options-futures-derivatives/ch08.md
        - 第9章 · 期权市场机制: books/finance/options-futures-derivatives/ch09.md
        - 第10章 · 股票期权的性质: books/finance/options-futures-derivatives/ch10.md
        - 第11章 · 期权交易策略: books/finance/options-futures-derivatives/ch11.md
        - 第12章 · 二叉树: books/finance/options-futures-derivatives/ch12.md
        - 第13章 · 维纳过程和伊藤引理: books/finance/options-futures-derivatives/ch13.md
        - 第14章 · 布莱克-斯科尔斯-默顿模型: books/finance/options-futures-derivatives/ch14.md
        - 第15章 · 雇员股票期权: books/finance/options-futures-derivatives/ch15.md
        - 第16章 · 股指期权与货币期权: books/finance/options-futures-derivatives/ch16.md
        - 第17章 · 期货期权: books/finance/options-futures-derivatives/ch17.md
        - 第18章 · 希腊值: books/finance/options-futures-derivatives/ch18.md
        - 第19章 · 波动率微笑: books/finance/options-futures-derivatives/ch19.md
        - 第20章 · 基本数值方法: books/finance/options-futures-derivatives/ch20.md
        - 第21章 · 风险价值: books/finance/options-futures-derivatives/ch21.md
        - 第22章 · 估计波动率与相关性: books/finance/options-futures-derivatives/ch22.md
        - 第23章 · 信用风险: books/finance/options-futures-derivatives/ch23.md
        - 第24章 · 信用衍生产品: books/finance/options-futures-derivatives/ch24.md
        - 第25章 · 奇异期权: books/finance/options-futures-derivatives/ch25.md
        - 第26章 · 再论模型和数值算法: books/finance/options-futures-derivatives/ch26.md
        - 第27章 · 鞅与测度: books/finance/options-futures-derivatives/ch27.md
        - "第28章 · 利率衍生产品: 标准市场模型": books/finance/options-futures-derivatives/ch28.md
        - 第29章 · 曲率调整、时间调整和二次调整: books/finance/options-futures-derivatives/ch29.md
        - "第30章 · 利率衍生产品: 短期利率模型": books/finance/options-futures-derivatives/ch30.md
        - "第31章 · 利率衍生产品: HJM与LMM模型": books/finance/options-futures-derivatives/ch31.md
        - 第32章 · 再谈互换: books/finance/options-futures-derivatives/ch32.md
        - 第33章 · 能源与商品衍生产品: books/finance/options-futures-derivatives/ch33.md
        - 第34章 · 实物期权: books/finance/options-futures-derivatives/ch34.md
        - 第35章 · 重大金融损失与借鉴: books/finance/options-futures-derivatives/ch35.md
        - 第36章 · 衍生产品市场的未来: books/finance/options-futures-derivatives/ch36.md
      - 量化金融面试实用指南:
        - 封面: books/finance/quant-finance-interview/index.md
        - 前言: books/finance/quant-finance-interview/preface.md
        - 符号说明: books/finance/quant-finance-interview/notations.md
        - 第1章 · 基本原则: books/finance/quant-finance-interview/ch01.md
        - 第2章 · 脑筋急转弯: books/finance/quant-finance-interview/ch02.md
        - 第3章 · 微积分与线性代数: books/finance/quant-finance-interview/ch03.md
        - 第4章 · 概率论: books/finance/quant-finance-interview/ch04.md
        - 第5章 · 随机过程与随机微积分: books/finance/quant-finance-interview/ch05.md
        - 第6章 · 金融: books/finance/quant-finance-interview/ch06.md
        - 第7章 · 算法与数值方法: books/finance/quant-finance-interview/ch07.md
        - 索引: books/finance/quant-finance-interview/index_term.md

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js
  - javascripts/pseudocode-render.js

extra:
  generator: false
  social:
    - icon: material/bookshelf
      link: https://github.com/uynajgi/yuulibrary
