site_name: Yuunagi Library
site_description: 个人的数字图书馆
docs_dir: docs
theme:
  name: material
  language: zh
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 切换浅色模式
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

nav:
  - 首页: index.md
  - 书籍:
    - 金融经济:
      - 量化金融面试实用指南:
        - 封面: books/finance/quant-finance-interview/index.md
        - 前言: books/finance/quant-finance-interview/preface.md
        - 符号说明: books/finance/quant-finance-interview/notations.md
        - 第1章 · 基本原则: books/finance/quant-finance-interview/ch01.md
        - 第2章 · 脑筋急转弯: books/finance/quant-finance-interview/ch02.md
        - 第3章 · 微积分与线性代数: books/finance/quant-finance-interview/ch03.md
        - 第4章 · 概率论: books/finance/quant-finance-interview/ch04.md
        - 第5章 · 随机过程与随机微积分: books/finance/quant-finance-interview/ch05.md
        - 第6章 · 金融: books/finance/quant-finance-interview/ch06.md
        - 第7章 · 算法与数值方法: books/finance/quant-finance-interview/ch07.md
        - 索引: books/finance/quant-finance-interview/index_term.md

use_directory_urls: false
markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
