site_name: BOOK_TITLE
site_description: BOOK_DESCRIPTION
docs_dir: docs
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
  features:
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight

nav:
  - 主页: index.md
  - 前言: preface.md
  - 符号说明: notations.md
  - CHAPTER_NAV_PLACEHOLDER
  - 索引: index_term.md

use_directory_urls: false
markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
