#!/usr/bin/env python3
"""Generate structured analysis for a paper and assemble _index.md.

Uses ReAct (LLM + read_section tool) to read the paper and fill a structured
template: 一句话概括 / 核心论证链 / 实验参数详解 / 批判性思考 / 局限性 /
关键公式速查 / 术语对照.

Cross-links are generated by scanning global-index.json for papers with
overlapping tags — never hallucinated.

Usage:
    python3 generate_paper_note.py <translated.md> --slug <slug> [--meta meta.json]
    python3 generate_paper_note.py <translated.md> --slug <slug> --papers-dir content/papers

Requires .env with DEEPSEEK_API_KEY (same as translate_chapters.py).
"""
import argparse
import asyncio
import json
import os
import re
import sys

# ── Config ───────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..", "..", "..", "..")

try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(PROJECT_ROOT, ".env"))
except ImportError:
    pass

API_KEY = os.environ.get("DEEPSEEK_API_KEY") or os.environ.get("OPENAI_API_KEY", "")
BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-v4-flash")
MAX_TOKENS = 16384
MAX_LOOPS = 8                   # section 模式需要更多轮（读多个 section + 生成）
LONG_PAPER_THRESHOLD = 200000  # chars — suggest book workflow above this (综述级别)；论文含大量公式/图会虚高
SECTION_MODE_THRESHOLD = 15000  # chars — < 全文塞 context；≥ 按 section 切

GLOBAL_INDEX_PATH = os.path.join(PROJECT_ROOT, "static", "pageindex", "global-index.json")


# ── System prompt for structured analysis ────────────────────────────────
SYSTEM_PROMPT = """你是学术论文深度分析助手。基于论文全文生成高质量结构化笔记。

## 🔴 输出格式（必须严格遵守）
你必须按顺序输出以下 7 个栏目，每个都不可缺少，用 `###` 标题分隔。
输出前先在脑海中检查：7 个栏目是否全部覆盖。

### 一句话概括
本文用什么方法（点名具体技术，如 DMRG/TEBD/PEPS 而非"数值方法"）做了什么、**核心结论是什么**（3-4 句，不要泛泛"提出了一种方法"，要说清楚方法名+针对什么问题+相比已有方法的关键优势）。

### 核心论证链
把论文逻辑主线拆成 5-8 个步骤，每步说清楚**"做了什么 + 为什么这么做 + 结论是什么"**。
不要像目录一样只写标题（"第三章讲了PEPS" ← 禁止），要写出逻辑推进关系。

### 实验参数详解
| 参数 | 数值 | 含义 |
把散落的参数集中成表。理论论文改为关键假设/条件表。

### 批判性思考
**1. ...** **2. ...** **3. ...**（至少 3 条）

每条必须包含**具体技术内容**（方法对比、复杂度分析、实验设置缺陷、假设检验缺失等）。
**禁止**：「有一定局限性」「值得进一步研究」「论文写得不够详细」等空泛评价。
好的例子：「MPS 蛇形映射二维时，割断单个键意味着二分法穿过 ~L 个物理连接，所需键维数 D ~ exp(L)」
坏的例子：「PEPS 算法比较复杂」

### 局限性
- ...（每个局限性必须具体：点名条件/假设/维度/时间尺度/系统大小的限制，要能映射到论文具体段落，至少 4 条）
- 反例：「论文未进行实验验证」← 太笼统。正例：「实时演化的纠缠壁垒——局域哈密顿量全局淬火下纠缠线性增长，所需 MPS 键维数 D ∝ e^(vt) 随模拟时间指数增长，中等时间后即不可行」

### 关键公式速查
**🔴 不要用表格**。表格的 `|` 和 LaTeX 的 `|` 冲突。用列表格式：

- $$\\mathcal{F} = (\\mathcal{H}^2 - E_c)/E_0$$ — 平移缩放，式 (2)
- $$T_k(\\mathcal{F}) \\simeq \\exp(2k\\sqrt{a^2 - \\mathcal{H}^2})$$ — 滤波器近似，式 (5)

每个公式独立一行，用 `$$...$$` 包裹，后跟破折号解释+出处。列 4-6 个。

### 术语对照
| 中文 | 英文 | 含义 |
列 5-10 个关键术语。

## 可选：深入讨论小节
在 7 个固定栏目之外，如果你觉得论文有值得深入讲解的点（论文里没展开的推导、
关键物理图像、与竞争方法的深度对比），可以加 1-2 个 `### 深入：xxx` 小节。
但不要因此省略任何固定栏目。

## 🔴 公式格式规则
- 行内公式用 `$...$`：`$E_{\\mathrm{max}}$`、`$\\mathcal{H}^2$`
- 行间公式用 `$$...$$`
- **禁止裸括号**：`(\\mathcal{H}^2)` 错，必须 `$\\mathcal{H}^2$`
- **禁止 Unicode 符号**：用 `\\times` 不用 `×`，`\\leq` 不用 `≤`
- **禁止在 markdown 表格单元格内放复杂公式**（`|` 冲突）

## 其他
- 不要寒暄（"以下是分析..."），直接从 `### 一句话概括` 开始
- 内容不足写"（本文未涉及）"，不要编造"""


# ── Paper loading: adaptive full-text / section mode ─────────────────────
def split_front_matter(content):
    """Split into (front_matter_str, body_str)."""
    if not content.startswith("---"):
        return "", content
    end = content.find("\n---", 3)
    if end < 0:
        return "", content
    nl = content.find("\n", end + 4)
    if nl < 0:
        return content, ""
    return content[: nl + 1], content[nl + 1 :]


def load_paper_sections(md_path):
    """Load paper and split into sections. Returns (sections_dict, is_full_mode).

    < SECTION_MODE_THRESHOLD → full mode (one "__full__" key)
    ≥ threshold → split by ## headings
    """
    with open(md_path, encoding="utf-8") as f:
        content = f.read()
    fm, body = split_front_matter(content)

    if len(body) < SECTION_MODE_THRESHOLD:
        return {"__full__": body, "__fm__": fm}, True

    # Split by ## headings (but not ### or deeper)
    sections = {"__fm__": fm}
    current_title = "_ preamble"
    current_lines = []

    for line in body.split("\n"):
        # # or ## heading (but not ### or deeper)
        m = re.match(r"^#{1,2}\s+(.+)$", line)
        if m and not line.startswith("###"):
            if current_lines:
                sections[current_title] = "\n".join(current_lines)
            current_title = m.group(1).strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_title] = "\n".join(current_lines)

    # Remove empty preamble if it's just whitespace
    if "_ preamble" in sections and not sections["_ preamble"].strip():
        del sections["_ preamble"]

    return sections, False


# ── read_section tool ────────────────────────────────────────────────────
READ_SECTION_TOOL = {
    "type": "function",
    "function": {
        "name": "read_section",
        "description": "读取论文的指定章节内容。用于按需查看论文不同部分（如实验、方法、结果）。",
        "parameters": {
            "type": "object",
            "properties": {
                "section": {
                    "type": "string",
                    "description": "章节标题（模糊匹配，如'实验''结论''摘要'）",
                }
            },
            "required": ["section"],
        },
    },
}


def execute_read_section(sections, section_name):
    """Fuzzy-match section name against available sections."""
    if "__full__" in sections:
        return sections["__full__"]  # full mode — return everything
    available = [k for k in sections if not k.startswith("__")]
    name_lower = section_name.lower()
    # Exact match first
    for k in available:
        if k == section_name:
            return sections[k]
    # Contains match
    matches = [k for k in available if name_lower in k.lower() or k.lower() in name_lower]
    if matches:
        return sections[matches[0]]
    return f"未找到章节'{section_name}'。可用章节：{available}"


# ── ReAct loop ───────────────────────────────────────────────────────────
REFLECTION_PROMPT = """## 自我审查

请仔细审视你刚才生成的分析，逐条检查以下问题：

1. **一句话概括** 是否包含了具体方法名和核心数值结果？
2. **核心论证链** 每一步是否说明了"为什么"而不仅是"做了什么"？
3. **实验参数详解** 表格是否至少有 4 行具体数值/参数？
4. **批判性思考** 每条是否包含具体的技术细节（不是"有一定局限"这种废话）？
5. **局限性** 是否列出了具体的、技术性的限制（而非笼统描述）？
6. **关键公式速查** 是否列出了 4-6 个带有编号和解释的核心公式？
7. **术语对照** 是否包含 5-10 个关键术语？

请逐一指出你第一次分析中**具体哪些栏目有缺陷**，然后输出完整修正版。如果某栏目已经够好就直接保留。
**输出修正版全文即可，不要加解释。**"""


async def generate_analysis(client, sections, is_full):
    """Run ReAct loop to generate structured analysis with self-reflection.

    Two-pass: (1) read sections + draft, (2) self-critique + improve.
    """
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]

    if is_full:
        paper_text = sections["__full__"]
        messages.append({
            "role": "user",
            "content": f"论文全文如下，请生成结构化分析：\n\n{paper_text}",
        })
        tools = None
    else:
        available = [k for k in sections if not k.startswith("__")]
        section_list = "\n".join(f"- {k}" for k in available)
        messages.append({
            "role": "user",
            "content": (
                f"论文有以下章节：\n{section_list}\n\n"
                "请按以下步骤操作：\n"
                "1. 用 read_section 工具逐个读取所有章节（不要只读一个就输出）\n"
                "2. 读完全部章节后，按 system prompt 的模板生成结构化分析\n"
                "3. 分析必须覆盖全部 7 个栏目（一句话概括/核心论证链/实验参数/批判性思考/局限性/关键公式速查/术语对照）"
            ),
        })
        tools = [READ_SECTION_TOOL]

    # ── Pass 1: read sections + generate draft ────────────────────────────
    draft = ""
    for loop in range(MAX_LOOPS):
        kwargs = {
            "model": MODEL,
            "messages": messages,
            "max_tokens": MAX_TOKENS,
            "extra_body": {"thinking": {"type": "disabled"}},
        }
        if tools:
            kwargs["tools"] = tools

        resp = await client.chat.completions.create(**kwargs)
        choice = resp.choices[0]
        msg = choice.message

        # Tool call — execute and continue
        if choice.finish_reason == "tool_calls" and msg.tool_calls:
            messages.append(msg.model_dump())
            for tc in msg.tool_calls:
                import json as _json
                args = _json.loads(tc.function.arguments or "{}")
                result = execute_read_section(sections, args.get("section", ""))
                messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})
            continue

        # Final answer from first pass
        draft = msg.content or ""
        break

    # Exceeded max loops without final answer
    if not draft:
        last = messages[-1]
        draft = last.get("content", "") if isinstance(last, dict) else (last.content or "")
    if not draft:
        return ""

    # ── Pass 2: self-critique + improve ───────────────────────────────────
    messages.append({"role": "assistant", "content": draft})
    messages.append({"role": "user", "content": REFLECTION_PROMPT})

    # Drop tools for the reflection pass — pure text generation
    resp = await client.chat.completions.create(
        model=MODEL,
        messages=messages,
        max_tokens=MAX_TOKENS,
        extra_body={"thinking": {"type": "disabled"}},
    )
    improved = resp.choices[0].message.content or draft
    return improved


# ── Cross-link generation ────────────────────────────────────────────────
def find_related_papers(tags, current_slug):
    """Scan global-index.json for papers with overlapping tags."""
    if not os.path.exists(GLOBAL_INDEX_PATH):
        return []
    with open(GLOBAL_INDEX_PATH, encoding="utf-8") as f:
        gi = json.load(f)
    papers = [d for d in gi.get("docs", []) if d.get("type") == "paper" and d.get("id") != current_slug]
    scored = []
    for p in papers:
        overlap = len(set(tags) & set(p.get("tags", [])))
        if overlap > 0:
            scored.append((overlap, p))
    scored.sort(key=lambda x: -x[0])
    return [p for _, p in scored[:5]]


def render_cross_link(related):
    """Render cross-link section. Empty if no related papers found."""
    if not related:
        return ""  # Don't write anything — no hallucinated links
    lines = ["### 延伸阅读", ""]
    for p in related:
        title = p.get("title", p.get("id", ""))
        desc = p.get("description", "")[:80]
        path = p.get("path", "")
        lines.append(f"- **[{title}]({path})** — {desc}")
    return "\n".join(lines) + "\n"


# ── Analysis post-processing ─────────────────────────────────────────────
def fix_bare_latex(text):
    """Fix bare-parenthesis LaTeX OUTSIDE math regions only.

    Never touches content inside $...$ or $$...$$ — those are already wrapped.
    Operating inside them would break $ pairing.
    """
    # Split into math and non-math segments, only fix non-math
    parts = re.split(r"(\$\$[\s\S]*?\$\$|\$[^$\n]+?\$)", text)
    result = []
    for part in parts:
        if part.startswith("$"):
            # Math region — leave as-is
            result.append(part)
        else:
            # Non-math — fix bare parentheses
            part = re.sub(r"\((\\(?:mathcal|mathbb|mathrm|mathbf)\{[a-zA-Z]+\})\)", r"$\1$", part)
            part = re.sub(r"\((\\hat\{[a-zA-Z]+\})\)", r"$\1$", part)
            part = re.sub(r"\((\\mathbb\{[A-Z]\})\)", r"$\1$", part)
            part = re.sub(r"\(([A-Z]_\{[a-zA-Z]+\})\)", r"$\1$", part)
            result.append(part)
    return "".join(result)


def strip_preamble(text):
    """Remove LLM preamble lines before the first ### heading."""
    lines = text.split("\n")
    result = []
    found_first_heading = False
    for line in lines:
        if not found_first_heading:
            if line.strip().startswith("###"):
                found_first_heading = True
                result.append(line)
            # skip lines before first ### (preamble/寒暄)
            continue
        result.append(line)
    return "\n".join(result)


# ── Heading demotion ──────────────────────────────────────────────────────
def demote_headings(body):
    """Demote all markdown headings by one level so _index.md has a single H1.

    Papers extracted by MinerU use # for every section (I. INTRODUCTION, etc.).
    Hugo page title comes from front matter `title`, so body headings should
    start at ## (H2).
    """
    lines = body.split("\n")
    result = []
    for line in lines:
        if line.startswith("##### "):
            result.append("#" + line)
        elif line.startswith("#### "):
            result.append("#" + line)
        elif line.startswith("### "):
            result.append("#" + line)
        elif line.startswith("## "):
            result.append("#" + line)
        elif line.startswith("# "):
            result.append("#" + line)
        else:
            result.append(line)
    return "\n".join(result)


# ── Assembly ─────────────────────────────────────────────────────────────
def assemble_index_md(front_matter, translation_body, analysis, cross_link):
    """Assemble the final _index.md."""
    # Fix bare LaTeX and strip preamble in analysis only
    analysis = strip_preamble(analysis)
    analysis = fix_bare_latex(analysis)
    # Demote headings in body (paper body uses # for sections → turn into ##/###)
    translation_body = demote_headings(translation_body)
    # Separate translation from analysis
    parts = [front_matter, "", translation_body.rstrip(), "", "---", "", "## 阅读笔记", "", analysis.rstrip()]
    if cross_link:
        parts.extend(["", cross_link.rstrip()])
    parts.append("")
    return "\n".join(parts)


# ── Main ─────────────────────────────────────────────────────────────────
async def run(args):
    from openai import AsyncOpenAI

    if not API_KEY:
        print("Error: DEEPSEEK_API_KEY not set. Check .env", file=sys.stderr)
        return 1

    md_path = args.translated_md
    if not os.path.isfile(md_path):
        print(f"Error: {md_path} not found", file=sys.stderr)
        return 1

    # Review paper detection
    with open(md_path, encoding="utf-8") as f:
        content = f.read()
    if len(content) > LONG_PAPER_THRESHOLD:
        print(f"⚠ 论文较长（{len(content)} 字符 > {LONG_PAPER_THRESHOLD}），可能是综述。")
        print(f"  建议走 book 流程翻译拆章：")
        print(f"  python3 .claude/skills/add-book-to-library/scripts/translate_chapters.py <dir>/ --seed-chapters 2")
        print(f"  翻译后手动组装到 content/papers/{args.slug}/_index.md")
        return 0

    # Load meta
    meta = {}
    if args.meta and os.path.isfile(args.meta):
        with open(args.meta, encoding="utf-8") as f:
            meta = json.load(f)

    # Determine output path
    papers_dir = args.papers_dir
    output_dir = os.path.join(papers_dir, args.slug)
    output_path = os.path.join(output_dir, "_index.md")

    if not os.path.isdir(output_dir):
        print(f"⚠ 目录不存在，创建：{output_dir}")
        os.makedirs(os.path.join(output_dir, "images"), exist_ok=True)

    # Load paper sections
    sections, is_full = load_paper_sections(md_path)
    mode_label = "全文模式" if is_full else f"section 模式（{len([k for k in sections if not k.startswith('__')])} 节）"
    print(f"论文加载：{len(content)} 字符 | {mode_label}")
    print(f"Provider: {BASE_URL} | Model: {MODEL}\n")

    client = AsyncOpenAI(api_key=API_KEY, base_url=BASE_URL)

    # Generate structured analysis
    print("生成结构化分析中...", flush=True)
    analysis = await generate_analysis(client, sections, is_full)
    if not analysis.strip():
        print("⚠ 结构化分析为空，可能 API 出错", file=sys.stderr)
        analysis = "*（结构化分析生成失败，请手动补充）*"

    # Cross-link
    tags = meta.get("tags", [])
    related = find_related_papers(tags, args.slug)
    cross_link = render_cross_link(related)
    if related:
        print(f"cross-link：找到 {len(related)} 篇相关论文")

    # Build front matter
    fm = sections.get("__fm__", "")
    if not fm:
        # Construct from meta
        fm_lines = ["---"]
        for k in ["title", "description", "date", "author", "year", "category", "weight"]:
            if k in meta:
                v = meta[k]
                if isinstance(v, list):
                    items = ", ".join(f'"{item}"' for item in v)
                    fm_lines.append(f"{k}: [{items}]")
                else:
                    fm_lines.append(f'{k}: "{v}"' if isinstance(v, str) else f"{k}: {v}")
        if "tags" in meta:
            fm_lines.append(f"tags: [{', '.join(repr(t) for t in meta['tags'])}]")
        if "links" in meta and isinstance(meta["links"], list):
            fm_lines.append("links:")
            for link in meta["links"]:
                fm_lines.append(f'  - name: "{link["name"]}"')
                fm_lines.append(f'    url: "{link["url"]}"')
        fm_lines.append("---")
        fm = "\n".join(fm_lines)

    # Translation body (strip front matter from content to get body)
    _, body = split_front_matter(content)

    # Assemble
    output = assemble_index_md(fm, body, analysis, cross_link)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"\n✅ 已生成：{output_path}")
    print(f"   正文 {len(body)} 字符 + 分析 {len(analysis)} 字符")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Generate structured paper note and assemble _index.md.")
    ap.add_argument("translated_md", help="path to translated markdown file")
    ap.add_argument("--slug", required=True, help="paper directory slug (e.g. berry-phase-solid-state-qubit)")
    ap.add_argument("--meta", help="JSON file with title/author/year/tags/category")
    ap.add_argument("--papers-dir", default="content/papers", help="papers directory (default: content/papers)")
    args = ap.parse_args()
    return asyncio.run(run(args))


if __name__ == "__main__":
    sys.exit(main())
